server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@172.16.3.28:1522/FREEPDB1
    username: SYSTEM
    password: 31875595
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolKPLCStaff
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

lct:
  africa:
    membership: http://192.168.0.32:8082/api/v1/membership/create-member
    membership2: http://192.168.0.32:8070/api/v1/membership/beneficiaries
    membership1: http://192.168.0.32:8070/api/v1/membership/staged/beneficiary
    membershipByCategoryId1: https://api.lctafrica.net/api/v1/membership/beneficiary/findByCategoryAndMemberNumber
    membershipByCategoryId: http://192.168.0.32:8070/api/v1/membership/beneficiary/findByCategoryAndMemberNumber
    membershipStatusUpdate: http://192.168.0.32:8070/api/v1/membership/beneficiaries/status/update