server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@172.16.3.28:1521/FREEPDB1
    username: SYSTEM
    password: 31875595
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolKPLCStaff
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

lct:
  africa:  ##http://api.lctafrica.net
    membership: http://api.lctafrica.net/api/v1/membership/beneficiaries
    membership1: http://api.lctafrica.net/api/v1/membership/staged/beneficiary
    membershipByCategoryId: http://api.lctafrica.net/api/v1/membership/beneficiary/findByCategoryAndMemberNumber
    membershipStatusUpdate: http://api.lctafrica.net/api/v1/membership/beneficiaries/status/update
    membershipUpdate: http://api.lctafrica.net/api/v1/membership/updateMember