server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@172.16.3.28:1522/FREEPDB1
    username: SYSTEM
    password: 31875595
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: false

## RUN PROJECT
## mvn spring-boot:run